include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_require_non_null_named_parameters
    - annotate_overrides
    - avoid_function_literals_in_foreach_calls
    - avoid_init_to_null
