include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_require_non_null_named_parameters
    - annotate_overrides
    - avoid_function_literals_in_foreach_calls
    - avoid_init_to_null
    - prefer_single_quotes
    - require_trailing_commas
    - sort_child_properties_last
    - sort_unnamed_constructors_first
    - sort_constructors_first
